export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';
export const UPDATE_WITH_NEW_POST = 'UPDATE_WITH_NEW_POST';
